# Generated by Django 5.1.7 on 2025-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
