# Generated by Django 5.1.7 on 2025-04-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_body_ckeditor_post_intro_ckeditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_ckeditor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro_ckeditor',
        ),
    ]
