# Generated by Django 5.1.7 on 2025-04-05 15:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_post_body_ckeditor_remove_post_intro_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_test',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
