# Generated by Django 5.1.7 on 2025-04-05 15:16

import trix.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_post_intro_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_test',
            field=trix.fields.TrixField(default='', verbose_name='intro_test'),
            preserve_default=False,
        ),
    ]
