# Generated by Django 5.1.7 on 2025-04-05 15:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post_intro_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro_test',
            field=tinymce.models.HTMLField(),
        ),
    ]
