# Generated by Django 5.1.7 on 2025-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_post_intro_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro_test',
        ),
    ]
