# Generated by Django 5.1.7 on 2025-04-07 08:35

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_post_intro_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_test',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
