# Generated by Django 5.1.7 on 2025-04-07 11:04

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prose_content',
            field=prose.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
