# Generated by Django 5.1.7 on 2025-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_post_prose_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
