# Generated by Django 5.1.7 on 2025-04-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_remove_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prose_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
