# Generated by Django 5.1.7 on 2025-04-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_rename_prose_content_post_content_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
