# Generated by Django 5.1.7 on 2025-04-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_post_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
