# Generated by Django 5.1.7 on 2025-04-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lead',
        ),
    ]
